# SERVER
server:
  port: 8081
  servlet:
    context-path: /order/
# SERVER - END

# SPRING
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://localhost:5434/order
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      idle-timeout: 5
      connection-timeout: 30000
      leak-detection-threshold: 2
  jpa:
    hibernate:
      ddl-auto: none

#  # SPRING - END
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/ambev

# MANAGEMENT - DONT REMOVE
management:
  endpoint:
    health:
      show-details: never
      cache:
        time-to-live: "30s"
    metrics:
      access: read_only
  endpoints:
    web:
      exposure:
        include: health

# MANAGEMENT - END

# SPRING DOC - BEGIN
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    configUrl: /order/v3/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /order/v3/api-docs
    enabled: true
    path: /swagger-ui.html
  show-actuator: true
# SPRING DOC - END

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG