## Demais configurações são herdadas do application-prod.yml
#server:
##  error:
##    include-stacktrace: never
##    include-binding-errors: never
##    include-exception: false
#  port: 8080
#  servlet:
#    context-path: /order/
#
#spring:
#  main:
#    lazy-initialization: true
#  #    web-application-type: servlet
#  #  jackson:
#  #    property-naming-strategy: SNAKE_CASE
#  datasource:
#    url: jdbc:postgresql://localhost:5432/gerenciador-pedido
#    username: postgres
#    password: gerdan
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      minimum-idle: 1                        # minimo de conexões abertas
#      maximum-pool-size: 10                  # maximo de conexões abertas
#      idle-timeout: 5                        # 5 minutos
#      connection-timeout: 30                 # 30 segundos
#      leak-detection-threshold: 2            # 2 segundos
#
#logging:
#  level:
#    br.com.avaliacao: DEBUG
#    org.springframework.security: DEBUG
#
