INSERT INTO Produto (id, descricao) VALUES (1, 'Notebook Gamer');
INSERT INTO Produto (id, descricao) VALUES (2, 'Smartphone Android');
INSERT INTO Produto (id, descricao) VALUES (3, 'Fone de Ouvido Bluetooth');
INSERT INTO Produto (id, descricao) VALUES (4, 'Mouse Sem Fio');
INSERT INTO Produto (id, descricao) VALUES (5, 'Teclado Mecânico');
INSERT INTO Produto (id, descricao) VALUES (6, 'Monitor Full HD');
INSERT INTO Produto (id, descricao) VALUES (7, 'Câmera DSLR');
INSERT INTO Produto (id, descricao) VALUES (8, 'Impressora Multifuncional');
INSERT INTO Produto (id, descricao) VALUES (9, 'Tablet 10 Polegadas');
INSERT INTO Produto (id, descricao) VALUES (10, 'HD Externo 1TB');